config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: %i[edit update]
  resources :doctors, only: %i[index show new create specialties] do
    resources :consultations, only: %i[new create]
    resources :reviews, only: %i[index new create]
  end
  get 'patients', to: 'doctors#patients'
  devise_for :users
  post '/consultations/confirm_consultation', to: 'consultations#confirm_consultation', as: :confirm_consultation
  resources :users do
    resources :consultations, only: %i[index show]
    resources :patient_records, only: %i[index new create]
    resources :messages, only: %i[nex create]
    # get '/medical_records', to: 'medical_records#show'
    # get '/medical_records/edit', to: 'medical_records#edit', as: :edit_medical_records
  end
  resources :patient_records, only: %i[edit update]
  resources :medical_records, only: %i[show edit update]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  resources :work_days, only: %i[create destroy]
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :user
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_record

  def show
    @medical_records = MedicalRecord.find(params[:id])
    authorize @medical_records
  end

  def edit
    @medical_record = MedicalRecord.find(params[:id])
    authorize @medical_record
  end

  def update
    @medical_record.update(medical_records_params)
    authorize @medical_record
    redirect_to @medical_record
  end

  private

  def set_record
    @medical_record = MedicalRecord.find(params[:id])
  end

  def medical_records_params
    params.require(:medical_record).permit(:blood, :allergies)
  end
end

app/views/medical_records/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10">
      <div class = "form-style">
        <%= simple_form_for(@medical_record) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :blood %>
          <%= f.input :allergies %>
        </div>
      </div>
      <div class="form-actions form-action-style">
        <%= f.button :submit, "Enviar", class: ' btn-submit btn-coral' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/medical_records/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 offset-sm-2">
      <% if policy(@medical_records).doctor_or_user? %>
      <h1>MedicalRecords of <%= @medical_records.user.first_name %> <%= @medical_records.user.last_name %></h1>
      <p>Tipo Sanguíneo: <%= @medical_records.blood %></p>
      <%= link_to 'Editar', edit_medical_record_path(@medical_records) %>
      <% else %>
      <p>Você não pode ver essas informações</p>
      <% end %>

    </div>
  </div>
</div>