config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: %i[edit update]
  resources :doctors, only: %i[index show new create specialties] do
    resources :consultations, only: %i[new create]
    resources :reviews, only: %i[index new create]
  end
  get 'patients', to: 'doctors#patients'
  devise_for :users
  post '/consultations/confirm_consultation', to: 'consultations#confirm_consultation', as: :confirm_consultation
  resources :users do
    resources :consultations, only: %i[index show]
    resources :patient_records, only: %i[index new create]
    resources :messages, only: %i[nex create]
    # get '/medical_records', to: 'medical_records#show'
    # get '/medical_records/edit', to: 'medical_records#edit', as: :edit_medical_records
  end
  resources :patient_records, only: %i[edit update]
  resources :medical_records, only: %i[show edit update]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  resources :work_days, only: %i[create destroy]
end

app/views/shared/_bankcodes.html.erb
<p>Código do seu banco</p>
<select class="select2" name="admin[bank_code]">
  <option label="001 - BANCO DO BRASIL S.A." value="integer:001">001 - BANCO DO BRASIL S.A.</option>
  <option label="003 - BANCO DA AMAZONIA S.A." value="string:003">003 - BANCO DA AMAZONIA S.A.</option>
  <option label="004 - BANCO DO NORDESTE DO BRASIL S.A." value="string:004">004 - BANCO DO NORDESTE DO BRASIL S.A.</option>
  <option label="019 - BANCO AZTECA DO BRASIL S.A." value="string:019">019 - BANCO AZTECA DO BRASIL S.A.</option>
  <option label="021 - BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO" value="string:021">021 - BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO</option>
  <option label="025 - BANCO ALFA S.A" value="string:025">025 - BANCO ALFA S.A</option>
  <option label="033 - BANCO SANTANDER BANESPA S.A." value="string:033">033 - BANCO SANTANDER BANESPA S.A.</option>
  <option label="037 - BANCO DO ESTADO DO PARÁ S.A." value="string:037">037 - BANCO DO ESTADO DO PARÁ S.A.</option>
  <option label="036 - Banco Bradesco BBI S/A" value="string:036">036 - Banco Bradesco BBI S/A</option>
  <option label="040 - BANCO CARGILL S.A." value="string:040">040 - BANCO CARGILL S.A.</option>
  <option label="041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A." value="string:041">041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.</option>
  <option label="044 - BANCO BVA S.A." value="string:044">044 - BANCO BVA S.A.</option>
  <option label="045 - BANCO OPPORTUNITY S.A." value="string:045">045 - BANCO OPPORTUNITY S.A.</option>
  <option label="047 - BANCO DO ESTADO DE SERGIPE S.A." value="string:047">047 - BANCO DO ESTADO DE SERGIPE S.A.</option>
  <option label="062 - HIPERCARD BANCO MÚLTIPLO S.A." value="string:062">062 - HIPERCARD BANCO MÚLTIPLO S.A.</option>
  <option label="063 - BANCO IBI S.A. - BANCO MÚLTIPLO" value="string:063">063 - BANCO IBI S.A. - BANCO MÚLTIPLO</option>
  <option label="065 - BANCO LEMON S.A." value="string:065">065 - BANCO LEMON S.A.</option>
  <option label="066 - BANCO MORGAN STANLEY S.A." value="string:066">066 - BANCO MORGAN STANLEY S.A.</option>
  <option label="069 - BPN BRASIL BANCO MÚLTIPLO S.A." value="string:069">069 - BPN BRASIL BANCO MÚLTIPLO S.A.</option>
  <option label="070 - BRB - BANCO DE BRASILIA S.A." value="string:070">070 - BRB - BANCO DE BRASILIA S.A.</option>
  <option label="072 - BANCO RURAL MAIS S.A." value="string:072">072 - BANCO RURAL MAIS S.A.</option>
  <option label="073 - BB BANCO POPULAR DO BRASIL S.A." value="string:073">073 - BB BANCO POPULAR DO BRASIL S.A.</option>
  <option label="074 - BANCO J. SAFRA S.A." value="string:074">074 - BANCO J. SAFRA S.A.</option>
  <option label="075 - BANCO CR2 S/A" value="string:075">075 - BANCO CR2 S/A</option>
  <option label="076 - BANCO KDB DO BRASIL S.A." value="string:076">076 - BANCO KDB DO BRASIL S.A.</option>
  <option label="077 - BANCO INTERMEDIUM S/A" value="string:077">077 - BANCO INTERMEDIUM S/A</option>
  <option label="079 - JBS BANCO S/A" value="string:079">079 - JBS BANCO S/A</option>
  <option label="081 - CONCÓRDIA BANCO S.A." value="string:081">081 - CONCÓRDIA BANCO S.A.</option>
  <option label="084 - BANCO UNIPRIME NORTE DO PARANA" value="string:084">084 - BANCO UNIPRIME NORTE DO PARANA</option>
  <option label="085 - CECRED - Cooperativa Central de Crédito Urbano" value="string:085">085 - CECRED - Cooperativa Central de Crédito Urbano</option>
  <option label="089 - CREDISAN - Cooperativa de Crédito Rural da Região da Mogiana" value="string:089">089 - CREDISAN - Cooperativa de Crédito Rural da Região da Mogiana</option>
  <option label="096 - BANCO BM&amp;F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A." value="string:096">096 - BANCO BM&amp;F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A.</option>
  <option label="099 - COOPERATIVA DE CRÉDITO UNIPRIME CENTRAL" value="string:099">099 - COOPERATIVA DE CRÉDITO UNIPRIME CENTRAL</option>
  <option label="104 - CAIXA ECONOMICA FEDERAL" value="string:104">104 - CAIXA ECONOMICA FEDERAL</option>
  <option label="107 - BANCO BBM S/A" value="string:107">107 - BANCO BBM S/A</option>
  <option label="121 - BANCO AGIPLAN S.A" value="string:121">121 - BANCO AGIPLAN S.A</option>
  <option label="136 - UNICRED - UNICRED OESTE CATARINENSE" value="string:136">136 - UNICRED - UNICRED OESTE CATARINENSE</option>
  <option label="151 - BANCO NOSSA CAIXA S.A." value="string:151">151 - BANCO NOSSA CAIXA S.A.</option>
  <option label="197 - Stone Pagamentos S.A." value="string:197">197 - Stone Pagamentos S.A.</option>
  <option label="208 - BANCO UBS PACTUAL S.A." value="string:208">208 - BANCO UBS PACTUAL S.A.</option>
  <option label="212 - BANCO ORIGINAL" value="string:212">212 - BANCO ORIGINAL</option>
  <option label="213 - BANCO ARBI S.A." value="string:213">213 - BANCO ARBI S.A.</option>
  <option label="214 - BANCO DIBENS S.A." value="string:214">214 - BANCO DIBENS S.A.</option>
  <option label="217 - BANCO JOHN DEERE S.A." value="string:217">217 - BANCO JOHN DEERE S.A.</option>
  <option label="218 - BANCO BONSUCESSO S.A." value="string:218">218 - BANCO BONSUCESSO S.A.</option>
  <option label="222 - BANCO CALYON BRASIL S.A." value="string:222">222 - BANCO CALYON BRASIL S.A.</option>
  <option label="224 - BANCO FIBRA S.A." value="string:224">224 - BANCO FIBRA S.A.</option>
  <option label="225 - BANCO BRASCAN S.A." value="string:225">225 - BANCO BRASCAN S.A.</option>
  <option label="229 - BANCO CRUZEIRO DO SUL S.A." value="string:229">229 - BANCO CRUZEIRO DO SUL S.A.</option>
  <option label="230 - UNICARD BANCO MÚLTIPLO S.A." value="string:230">230 - UNICARD BANCO MÚLTIPLO S.A.</option>
  <option label="233 - BANCO GE CAPITAL S.A." value="string:233">233 - BANCO GE CAPITAL S.A.</option>
  <option label="237 - BANCO BRADESCO S.A." value="string:237">237 - BANCO BRADESCO S.A.</option>
  <option label="241 - BANCO CLASSICO S.A." value="string:241">241 - BANCO CLASSICO S.A.</option>
  <option label="243 - BANCO MÁXIMA S.A." value="string:243">243 - BANCO MÁXIMA S.A.</option>
  <option label="246 - BANCO ABC BRASIL S.A." value="string:246">246 - BANCO ABC BRASIL S.A.</option>
  <option label="248 - BANCO BOAVISTA INTERATLANTICO S.A." value="string:248">248 - BANCO BOAVISTA INTERATLANTICO S.A.</option>
  <option label="249 - BANCO INVESTCRED UNIBANCO S.A." value="string:249">249 - BANCO INVESTCRED UNIBANCO S.A.</option>
  <option label="250 - BANCO SCHAHIN S.A." value="string:250">250 - BANCO SCHAHIN S.A.</option>
  <option label="254 - PARANÁ BANCO S.A." value="string:254">254 - PARANÁ BANCO S.A.</option>
  <option label="260 - NU PAGAMENTOS S.A." value="string:260">260 - NU PAGAMENTOS S.A.</option>
  <option label="263 - BANCO CACIQUE S.A." value="string:263">263 - BANCO CACIQUE S.A.</option>
  <option label="265 - BANCO FATOR S.A." value="string:265">265 - BANCO FATOR S.A.</option>
  <option label="266 - BANCO CEDULA S.A." value="string:266">266 - BANCO CEDULA S.A.</option>
  <option label="300 - BANCO DE LA NACION ARGENTINA" value="string:300">300 - BANCO DE LA NACION ARGENTINA</option>
  <option label="318 - BANCO BMG S.A." value="string:318">318 - BANCO BMG S.A.</option>
  <option label="341 - BANCO ITAÚ S.A." value="string:341">341 - BANCO ITAÚ S.A.</option>
  <option label="356 - BANCO ABN AMRO REAL S.A." value="string:356">356 - BANCO ABN AMRO REAL S.A.</option>
  <option label="366 - BANCO SOCIETE GENERALE BRASIL S.A." value="string:366">366 - BANCO SOCIETE GENERALE BRASIL S.A.</option>
  <option label="370 - BANCO WESTLB DO BRASIL S.A." value="string:370">370 - BANCO WESTLB DO BRASIL S.A.</option>
  <option label="376 - BANCO J.P. MORGAN S.A." value="string:376">376 - BANCO J.P. MORGAN S.A.</option>
  <option label="389 - BANCO MERCANTIL DO BRASIL S.A." value="string:389">389 - BANCO MERCANTIL DO BRASIL S.A.</option>
  <option label="394 - BANCO FINASA BMC S.A." value="string:394">394 - BANCO FINASA BMC S.A.</option>
  <option label="399 - HSBC BANK BRASIL S.A. - BANCO MULTIPLO" value="string:399">399 - HSBC BANK BRASIL S.A. - BANCO MULTIPLO</option>
  <option label="409 - UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A." value="string:409">409 - UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A.</option>
  <option label="412 - BANCO CAPITAL S.A." value="string:412">412 - BANCO CAPITAL S.A.</option>
  <option label="422 - BANCO SAFRA S.A." value="string:422">422 - BANCO SAFRA S.A.</option>
  <option label="453 - BANCO RURAL S.A." value="string:453">453 - BANCO RURAL S.A.</option>
  <option label="456 - BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S/A" value="string:456">456 - BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S/A</option>
  <option label="464 - BANCO SUMITOMO MITSUI BRASILEIRO S.A." value="string:464">464 - BANCO SUMITOMO MITSUI BRASILEIRO S.A.</option>
  <option label="473 - BANCO CAIXA GERAL - BRASIL S.A." value="string:473">473 - BANCO CAIXA GERAL - BRASIL S.A.</option>
  <option label="477 - CITIBANK N.A." value="string:477">477 - CITIBANK N.A.</option>
  <option label="487 - DEUTSCHE BANK S.A. - BANCO ALEMAO" value="string:487">487 - DEUTSCHE BANK S.A. - BANCO ALEMAO</option>
  <option label="488 - JPMORGAN CHASE BANK, NATIONAL ASSOCIATION" value="string:488">488 - JPMORGAN CHASE BANK, NATIONAL ASSOCIATION</option>
  <option label="492 - ING BANK N.V." value="string:492">492 - ING BANK N.V.</option>
  <option label="494 - BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY" value="string:494">494 - BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY</option>
  <option label="495 - BANCO DE LA PROVINCIA DE BUENOS AIRES" value="string:495">495 - BANCO DE LA PROVINCIA DE BUENOS AIRES</option>
  <option label="505 - BANCO CREDIT SUISSE (BRASIL) S.A." value="string:505">505 - BANCO CREDIT SUISSE (BRASIL) S.A.</option>
  <option label="582 - UNICRED UNIÃO" value="string:582">582 - UNICRED UNIÃO</option>
  <option label="600 - BANCO LUSO BRASILEIRO S.A." value="string:600">600 - BANCO LUSO BRASILEIRO S.A.</option>
  <option label="604 - BANCO INDUSTRIAL DO BRASIL S.A." value="string:604">604 - BANCO INDUSTRIAL DO BRASIL S.A.</option>
  <option label="610 - BANCO VR S.A." value="string:610">610 - BANCO VR S.A.</option>
  <option label="611 - BANCO PAULISTA S.A." value="string:611">611 - BANCO PAULISTA S.A.</option>
  <option label="612 - BANCO GUANABARA S.A." value="string:612">612 - BANCO GUANABARA S.A.</option>
  <option label="613 - BANCO PECUNIA S.A." value="string:613">613 - BANCO PECUNIA S.A.</option>
  <option label="623 - BANCO PANAMERICANO S.A." value="string:623">623 - BANCO PANAMERICANO S.A.</option>
  <option label="626 - BANCO FICSA S.A." value="string:626">626 - BANCO FICSA S.A.</option>
  <option label="630 - BANCO INTERCAP S.A." value="string:630">630 - BANCO INTERCAP S.A.</option>
  <option label="633 - BANCO RENDIMENTO S.A." value="string:633">633 - BANCO RENDIMENTO S.A.</option>
  <option label="634 - BANCO TRIANGULO S.A." value="string:634">634 - BANCO TRIANGULO S.A.</option>
  <option label="637 - BANCO SOFISA S.A." value="string:637">637 - BANCO SOFISA S.A.</option>
  <option label="638 - BANCO PROSPER S.A." value="string:638">638 - BANCO PROSPER S.A.</option>
  <option label="643 - BANCO PINE S.A." value="string:643">643 - BANCO PINE S.A.</option>
  <option label="653 - BANCO INDUSVAL S.A." value="string:653">653 - BANCO INDUSVAL S.A.</option>
  <option label="654 - BANCO A.J. RENNER S.A." value="string:654">654 - BANCO A.J. RENNER S.A.</option>
  <option label="655 - BANCO VOTORANTIM S.A." value="string:655">655 - BANCO VOTORANTIM S.A.</option>
  <option label="707 - BANCO DAYCOVAL S.A." value="string:707">707 - BANCO DAYCOVAL S.A.</option>
  <option label="719 - BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A." value="string:719">719 - BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A.</option>
  <option label="721 - BANCO CREDIBEL S.A." value="string:721">721 - BANCO CREDIBEL S.A.</option>
  <option label="734 - BANCO GERDAU S.A" value="string:734">734 - BANCO GERDAU S.A</option>
  <option label="738 - BANCO MORADA S.A." value="string:738">738 - BANCO MORADA S.A.</option>
  <option label="739 - BANCO BGN S.A." value="string:739">739 - BANCO BGN S.A.</option>
  <option label="740 - BANCO BARCLAYS S.A." value="string:740">740 - BANCO BARCLAYS S.A.</option>
  <option label="741 - BANCO RIBEIRAO PRETO S.A." value="string:741">741 - BANCO RIBEIRAO PRETO S.A.</option>
  <option label="743 - BANCO EMBLEMA S.A." value="string:743">743 - BANCO EMBLEMA S.A.</option>
  <option label="745 - BANCO CITIBANK S.A." value="string:745">745 - BANCO CITIBANK S.A.</option>
  <option label="746 - BANCO MODAL S.A." value="string:746">746 - BANCO MODAL S.A.</option>
  <option label="747 - BANCO RABOBANK INTERNATIONAL BRASIL S.A." value="string:747">747 - BANCO RABOBANK INTERNATIONAL BRASIL S.A.</option>
  <option label="748 - BANCO COOPERATIVO SICREDI S.A." value="string:748">748 - BANCO COOPERATIVO SICREDI S.A.</option>
  <option label="749 - BANCO SIMPLES S.A." value="string:749">749 - BANCO SIMPLES S.A.</option>
  <option label="751 - DRESDNER BANK BRASIL S.A. BANCO MULTIPLO" value="string:751">751 - DRESDNER BANK BRASIL S.A. BANCO MULTIPLO</option>
  <option label="752 - BANCO BNP PARIBAS BRASIL S.A." value="string:752">752 - BANCO BNP PARIBAS BRASIL S.A.</option>
  <option label="753 - NBC BANK BRASIL S. A. - BANCO MÚLTIPLO" value="string:753">753 - NBC BANK BRASIL S. A. - BANCO MÚLTIPLO</option>
  <option label="756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB" value="string:756">756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB</option>
  <option label="757 - BANCO KEB DO BRASIL S.A." value="string:757">757 - BANCO KEB DO BRASIL S.A.</option>
</select>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <% if signed_in? %>
    <% if current_user.doctor.nil? %>
      <div class="about">
        <p><%= link_to "Sou um médico", new_doctor_path %></p>
      </div>
    <% else %>
      <div class="about"></div>
    <% end %>
  <% else %>
    <div class="about"></div>
  <% end %>
  <div class ="about">
    <p><%= link_to 'Sobre Nós', about_path%></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
 <!-- Logo -->
 <%= link_to root_path, class: "navbar-wagon-brand" do %>
 <%= image_tag "logo.png", height: 50 %>
 <% end %>

 <!-- Right Navigation -->
 <div class="navbar-wagon-right hidden-sm-down">

   <% if user_signed_in? %>

   <!-- Avatar with dropdown menu -->
   <div class="navbar-wagon-item">
     <div class="dropdown">
       <%= cl_image_tag current_user.profile_picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
       <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

         <!-- Links when logged in -->
         <li>
           <% if policy(Doctor).doctor? %>
             <%= link_to patients_path, class: "navbar-wagon-item navbar-wagon-link" do %>
              <i class="fas fa-user-md"></i> Área do Médico
             <% end %>
           <% end %>
         </li>
         <li>
           <%= link_to user_consultations_path(current_user.id) do %>
           <i class="fa fa-archive" aria-hidden="true"></i> Minhas consultas
           <% end %>

         </li>
      <!--    <li>
           <%= link_to "#" do %>
           <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
           <% end %>
         </li> -->
       <!--   <li>
           <%= link_to "#" do %>
           <i class="fa fa-envelope-open" aria-hidden="true"></i> Mensagens
           <% end %>
         </li> -->
         <li>
           <%= link_to edit_user_registration_path do %>
           <i class="fa fa-edit"></i> Atualizar cadastro
           <% end %>
         </li>
    <!--      <li>
           <%= link_to "#" do %>
           <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
           <% end %>
         </li> -->
         <li>
           <%= link_to destroy_user_session_path, method: :delete do %>
           <i class="fa fa-sign-out" aria-hidden="true"></i> <%= t(".sign_out", default: "Log out") %>
           <% end %>
         </li>
       </ul>
     </div>
   </div>
   <% else %>
   <!-- Login link (when logged out) -->
   <%= link_to t(".sign_in", default: "Entrar"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn-coral" %>
   <% end %>
 </div>
</div>