config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: %i[edit update]
  resources :doctors, only: %i[index show new create specialties] do
    resources :consultations, only: %i[new create]
    resources :reviews, only: %i[index new create]
  end
  get 'patients', to: 'doctors#patients'
  devise_for :users
  post '/consultations/confirm_consultation', to: 'consultations#confirm_consultation', as: :confirm_consultation
  resources :users do
    resources :consultations, only: %i[index show]
    resources :patient_records, only: %i[index new create]
    resources :messages, only: %i[nex create]
    # get '/medical_records', to: 'medical_records#show'
    # get '/medical_records/edit', to: 'medical_records#edit', as: :edit_medical_records
  end
  resources :patient_records, only: %i[edit update]
  resources :medical_records, only: %i[show edit update]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  resources :work_days, only: %i[create destroy]
end

app/models/patient_record.rb
class PatientRecord < ApplicationRecord
  belongs_to :patient, class_name: 'User', foreign_key: 'patient_id'
  belongs_to :doctor
end

app/controllers/patient_records_controller.rb
class PatientRecordsController < ApplicationController
  before_action :set_patient_record, only: %i[edit update]

  def index
    @patient = User.find(params[:user_id])
    @patient_records = policy_scope(PatientRecord.where(patient: @patient))
    @patient_records = @patient_records.where(doctor: current_user.doctor)
    @message = Message.new
  end

  def new
    @user = User.find(params[:user_id])
    @patient_record = PatientRecord.new
    authorize @patient_record
  end

  def create
    patient = User.find(params[:user_id])
    @patient_record = PatientRecord.new(patient_record_params)
    @patient_record.patient = patient
    @patient_record.doctor = current_user.doctor
    authorize @patient_record
    if @patient_record.save
      redirect_to user_patient_records_path(@patient_record.patient), notice: 'Prontuário criado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @patient_record.update(patient_record_params)
      redirect_to user_patient_records_path(@patient_record.patient), notice: 'Prontuário atualizado com sucesso!'
    else
      render :edit
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
    authorize @patient_record
  end

  def patient_record_params
    params.require(:patient_record).permit(:entry)
  end

  def message_params
    params.require(:patient_record).permit(:message)
  end
end

app/views/patient_records/edit.html.erb
<div class = "main-container-edit-patients-records">
  <div class="container" style = "margin-top: 30px;font-size: 0px">
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class = "container-texto">
          <div class = titulo>
            <h2>Prontuário Médico</h2>
            <p class="detalhe-page-prontuario"></p>
          </div>
        </div>

        <div class = "form-style">
          <%= simple_form_for(@patient_record) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :entry, as: :wysihtml5, wysihtml5: { toolbar:{"fa": true}, locale: "pt-BR" } %>
          </div>
        </div>
        <div class = "button-edit-new">
          <div class="form-actions form-action-style">
            <%= f.button :submit, "Salvar", class: 'btn-coral' %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/patient_records/index.html.erb
<div class = main-container-edit-patients-records >  <div class = "container-texto" style = "margin-top: 60px;">
  <div class = titulo>
    <h2>Prontuário Médico</h2>
    <p class="detalhe-page-prontuario"></p>
  </div>
  <div class="container box-prontuario-info">

    <div class="row">
      <div class="col-xs-12 col-md-10 offset-md-1">
        <h2 style = "padding-bottom: 5px; padding-top: 20px">Paciente: <%= @patient.first_name %> <%= @patient.last_name %></h2>
        <% if @patient_records != [] %>
        <% @patient_records.each do |patient_record| %>
        <p><%= sanitize(patient_record.entry) %></p>
        <div class = "button-edit-new">
          <%= link_to patients_path, class: 'btn-branco-coral' do %>Voltar
          <% end %>
          <%= link_to edit_patient_record_path(patient_record), class: 'btn-coral' do %>
          Editar
          <% end %>
          <% end %>
          <% else %>
          <%= link_to new_user_patient_record_path, class: 'btn-coral', style:"margin-right: 16px;" do %>
          Criar Prontuário
          <% end %>
          <% end %>
          <button type="button" class="btn-coral" data-toggle="modal" data-target="#exampleModal">
            Enviar Mensagem
          </button>
        </div>
        <!-- Button trigger modal -->

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Enviar Mensagem</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class = "form-style">
                  <form action="<%= user_messages_path(@patient) %>" method="POST">
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <div class="form-inputs">
                      <div class="form-group">
                        <label for="exampleFormControlTextarea1">Sua mensagem</label>
                        <textarea class="form-control" name="message[content]" id="exampleFormControlTextarea1" rows="3"></textarea>
                      </div>

                    </div>
                  </div>
                  <div class = "button-edit-new">
                    <div class="form-actions form-action-style">
                      <input type="submit" value="Enviar" class="btn-coral">
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patient_records/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-10">
      <div class = "form-style">
        <%= simple_form_for([@user, @patient_record]) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :entry, as: :wysihtml5, wysihtml5: { toolbar:{"fa": true}, locale: "pt-BR" } %>
        </div>
      </div>
      <div class="form-actions form-action-style">
        <%= f.button :submit, "Salvar", class: ' btn-submit btn-coral' %>
      </div>
      <% end %>
    </div>
  </div>
</div>