config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: %i[edit update]
  resources :doctors, only: %i[index show new create specialties] do
    resources :consultations, only: %i[new create]
    resources :reviews, only: %i[index new create]
  end
  get 'patients', to: 'doctors#patients'
  devise_for :users
  post '/consultations/confirm_consultation', to: 'consultations#confirm_consultation', as: :confirm_consultation
  resources :users do
    resources :consultations, only: %i[index show]
    resources :patient_records, only: %i[index new create]
    resources :messages, only: %i[nex create]
    # get '/medical_records', to: 'medical_records#show'
    # get '/medical_records/edit', to: 'medical_records#edit', as: :edit_medical_records
  end
  resources :patient_records, only: %i[edit update]
  resources :medical_records, only: %i[show edit update]
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  resources :work_days, only: %i[create destroy]
end

app/models/doctor.rb
require 'json'
require 'open-uri'
require 'pagarme'

class Doctor < ApplicationRecord
  include PgSearch
  belongs_to :user
  has_many :messages
  has_many :reviews, dependent: :destroy
  has_many :consultations, dependent: :destroy
  has_many :orders
  has_many :patient_record, dependent: :destroy
  has_many :doctor_specialties, dependent: :destroy
  has_many :specialties, through: :doctor_specialties, dependent: :destroy
  has_one :work_schedule, dependent: :destroy
  monetize :price_cents
  geocoded_by :address
  validates :address, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :crm, presence: true, uniqueness: true

  after_validation :set_coordinates, :create_bank_account, :create_recipient
  after_save :create_schedule
  pg_search_scope :global_search,
                  associated_against: {
                  user: [:first_name, :last_name],
                  specialties: [:name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  private

  def create_schedule
    WorkSchedule.create!(doctor: self)
  end

  def set_coordinates
    # self.description = "https://maps.googleapis.com/maps/api/geocode/json?address=#{self.address}&key=#{ENV['GOOGLE_API_KEY']}"
    url = "https://maps.googleapis.com/maps/api/geocode/json?address=#{self.address}&key=#{ENV['GOOGLE_API_KEY']}"
    api_response = open(URI.escape(url)).read
    coordinates = JSON.parse(api_response)
    # self.description = coordinates['results']
    self.latitude = coordinates["results"].first["geometry"]["location"]["lat"]
    self.longitude = coordinates["results"].first["geometry"]["location"]["lng"]
  end

  def create_bank_account
    PagarMe.api_key        = ENV["PAGARME_API_KEY"]
    PagarMe.encryption_key = ENV["PAGARME_ENCRYPTION_KEY"]

    bank_account = PagarMe::BankAccount.new({
                                              bank_code: self.bank_code,
                                              agencia: self.agency,
                                              agencia_dv: self.agency_vd,
                                              conta: self.account,
                                              conta_dv: self.account_vd,
                                              legal_name: "#{self.user.first_name} #{self.user.last_name}",
                                              document_number: '04499225027'
    })

    bank_account.create
    self.bank_account_id = bank_account.id
    self
  end

  def create_recipient
    PagarMe.api_key        = ENV["PAGARME_API_KEY"]
    PagarMe.encryption_key = ENV["PAGARME_ENCRYPTION_KEY"]

    recipient = PagarMe::Recipient.new({
                                         bank_account_id: self.bank_account_id.to_s,
                                         transfer_enabled: true,
                                         transfer_interval: "daily"
    }).create
    self.recipient_id = recipient.id
    self
  end
end

app/controllers/doctors_controller.rb
require 'pagarme'

class DoctorsController < ApplicationController
  helper_method :consultation_array
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    if params[:keywords].empty?
      @doctors = policy_scope(Doctor.all)
    else
      @doctors = policy_scope(Doctor.global_search(params[:keywords]))
    end
    @doctors = @doctors.near([@latitude, @longitude], 10, units: :km) if (@latitude.present? && @longitude.present?)
    @markers = @doctors.map do |doctor|
      {
        lng: doctor.longitude,
        lat: doctor.latitude,
        infoWindow: { content: render_to_string(partial: "infowindow", locals: { doctor: doctor }) }
      }
    end
  end

  def show
    @consultation = Consultation.new
    @doctor = Doctor.find(params[:id])
    @reviews = Review.where(doctor: @doctor)
    @general_rating = set_rating(@reviews)
    @markers = [{
        lng: @doctor.longitude,
        lat: @doctor.latitude,
        infoWindow: { content: render_to_string(partial: "infowindow", locals: { doctor: @doctor }) }
      }]

    authorize @doctor
    @review = Review.new
  end

  def new
    @doctor = Doctor.new
    @specialties = Specialty.all
    @banks = Bank.all
    authorize @doctor
  end

  def create
    @banks = Bank.all
    @doctor = Doctor.new(doctor_params)
    @doctor.bank_code = Bank.find(@doctor.bank_code).code
    @doctor.user = current_user
    authorize @doctor
    if @doctor.save
      # create_work_schedule(@doctor)
      WorkSchedule.create!(doctor: @doctor)
      create_doctor_specialties(@doctor, params[:doctor][:specialties])
    else
      render :new
    end
  end

  def patients
    @consultations = Consultation.where(doctor: current_user.doctor)
    @patients = @consultations.map do |consultation|
      consultation.patient
    end
    @patients.each { |patient| authorize patient }
    authorize User.new
  end

  private

  def set_rating(reviews)
    if reviews.size >= 1
      rating_sum = 0
      reviews.each do |review|
        rating_sum += review.rating
      end
      rating = rating_sum / reviews.size if reviews.size >= 1
      rating
    else
      return 0
    end
  end

  def create_doctor_specialties(doctor, specialties)
    specialties.delete_at(0)
    specialties.each do |specialty_id|
      specialty = Specialty.find(specialty_id.to_i)
      DoctorSpecialty.create!(doctor: doctor, specialty: specialty)
    end
    redirect_to doctor
  end

  def doctor_params
    params.require(:doctor).permit(
      :description,
      :academic_formation,
      :price,
      :address,
      :crm,
      :competence,
      :since,
      :specialties,
      :bank_code,
      :agency,
      :agency_vd,
      :account,
      :account_vd
    )
  end

  def consultation_array(consultations)
    consultations_array = []
    consultations.each do |consultation|
      consultations_array << { title: consultation.patient.first_name, start: consultation.start_time, end: consultation.end_time }
    end
    return consultations_array.to_json
  end
end

app/views/doctors/index.html.erb
<div class = "global">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <div class= "cards-list">
          <% @doctors.each do |doctor| %>
          <% @reviews = Review.where(doctor: doctor) %>
          <% def set_rating(reviews)
            if reviews.size >= 1
              rating_sum = 0
              reviews.each do |review|
                rating_sum += review.rating
              end
              rating = rating_sum / reviews.size if reviews.size >= 1
              rating
            else
              return 0
            end
          end %>
          <%= link_to doctor do %>
          <div class = "doctor-information">
            <div class = "doctor-avatar">
              <%= cl_image_tag (doctor.user.profile_picture), class:"avatar-larger" %>
            </div>

            <div class="doctor-info-box">
              <div class = "doctor-name">
                <h1>
                  <%= set_gender(doctor) %> <%= doctor.user.first_name %> <%= doctor.user.last_name %>
                </h1>
              </div>
              <div class ="doctor-specialty">
                <p>
                 <% doctor.specialties.each do |specialty|%>
                 <%= specialty.name %>
                 <% end %>
               </p>
             </div>

           </div>
           <div class="icons">
            <p>
              <% rating = set_rating(@reviews) %>
              <% rating.times do |r| %>
                <i class="fas fa-star"></i>
              <% end %>
            </p>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
    <div id="map-box" class="col-md-6">
      <div id="map"
      style="width: 100%; position: sticky !important; height: 100vh; top: 0 !important;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
</div>
</div>

app/views/doctors/new.html.erb
<div class="container-form">

 <div class = "destaque-new-user">
  <p>Solicite através deste formulário o seu perfil de médico.</p>
</div>


<div class="row">
  <div class="col-xs-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
    <div class = "container-texto">
      <div class = titulo>
        <h2>Informações necessárias</h2>
        <p class="detalhe-page-new-doctor"></p>
      </div>
    </div>
    <div class = "container-out-form">
      <div class = "form-style">
        <%= simple_form_for(@doctor) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :description %>
          <%= f.input :academic_formation %>
          <%= f.input :competence %>
          <%= f.input :since %>
          <%= f.input :price %>
          <%= f.input :address, :id => 'doctor_address' %>
          <%= f.input :crm %>
          <%= f.input :specialties, collection: @specialties, input_html: { multiple: true, class: 'select2' } %>
          <%= f.input :bank_code, collection: @banks, input_html: { class: 'select2' } %>
          <%= f.input :agency %>
          <%= f.input :agency_vd %>
          <%= f.input :account %>
          <%= f.input :account_vd %>
        </div>
      </div>
      <div class="form-actions form-action-style">
        <%= f.button :submit, "Enviar", class: ' btn-submit btn-coral' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/doctors/patients.html.erb
<div class="container outer-box">
  <div class="row d-flex justify-content-between" style="margin-bottom: -25px;">
    <div class= "col-xs-12 col-md-4 ">
      <div class ="accordion apply-box-patients" id="accordion">
        <div class="card">
          <div class="card-header" id="headingOne">
            <h5 class="mb-0 edit-title">
              <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <h2>Próximas Consultas</h2>
              </button>
            </h5>
          </div>
          <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
             <% @consultations = @consultations.order("start_time ASC") %>
             <% @consultations.each do |consultation| %>
             <% if consultation.start_time > Time.now %>
             <% date = consultation.start_time %>
             <p><%= consultation.patient.first_name %> : <%= l(date, format: "%A, %d de %B de %Y às %H:%M") %> </p>
             <% end %>
             <% end %>
           </div>
         </div>
       </div>
       <div class="card">
        <div class="card-header" id="headingTwo">
          <h5 class="mb-0 edit-title">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
             <h2>Meus Pacientes</h2>
           </button>
         </h5>
       </div>
       <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
          <% @patients.sort_by!{|patient| patient.first_name} %>
          <% @patients.uniq! %>
          <% @patients.each do |patient| %>
          <%= link_to user_patient_records_path(patient) do %>
          <p><%= patient.first_name %> <%= patient.last_name %></p>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="apply-box-patients  p-3 mb-5 rounded col-xs-12 col-md-8 calendar-box">
  <div id="calendar"></div>
  <div class="container-schedule-doctor">
    <h3 style = "padding-left: 5px">Marcar dias disponíveis para atendimento</h3>
    <div class = "flex-days">
    <% 7.times do |number| %>
        <%= link_to work_days_path(week_day: number), method: :post, class: "btn-branco-patients" do %>
        <%= t(Date::DAYNAMES[number]) %>
        <% end %>
    <% end %>
    </div>
  </div>
  <div class="container-calendar-doctor">
    <h3 style = "padding-left: 5px">Dias disponibilizados para agendamento de consultas</h3>
    <div class = "flex-days">
    <% current_user.doctor.work_schedule.work_days.each do |weekday| %>
        <%= link_to work_day_path(id: weekday.id), method: :delete, class: "btn-coral-patients" do %>
        <%= t(Date::DAYNAMES[weekday.day]) %>
        <% end %>
    <% end %>
    </div>
  </div>
</div>

</div>
</div>


<script>
  $("#calendar").fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek,agendaDay,list'
    },
    buttonText: {
      today:    'hoje',
      month:    'mês',
      week:     'semana',
      day:      'dia',
      list:     'lista'
    },
    locale: 'pt-BR',
    events: <%= raw (consultation_array(@consultations)) %>,
  });
</script>

app/views/doctors/show.html.erb
<div class="show-page">
  <div class="doc-show">

    <section class="profile-doc-section">
      <div class="profile-doc-wrapper">

        <div class="profile-doc-inner">

          <div class="profile-doc-main">

            <div class="profile-doc-main-avatar">
              <%= cl_image_tag @doctor.user.profile_picture, height: 150, style:"border-radius: 50%;" %>
            </div>
            <div class="profile-doc-main-title">
              <h1 class="profile-doc-main-title-name">
                <%= set_gender(@doctor) %> <%= @doctor.user.first_name %> <%= @doctor.user.last_name %>
              </h1>
              <h2 class="profile-doc-main-title-desc">
                <div class="profile-doc-main-title-desc-top">
                  <% @doctor.specialties.each do |specialty| %>
                  <%= specialty.name %>
                  <% end %>
                  · $$$
                </div>
                <div class="profile-doc-main-title-desc-bottom">
                  <% if @general_rating > 0 %>
                  <% @general_rating.times do |star| %>
                  <i class="fas fa-star star-icon"></i>
                  <% end %> (<%= @reviews.size %> avaliações)
                  <% end %>
                </div>
              </h2>
            </div>
          </div>

          <div class="profile-doc-contact">
            <div class="profile-doc-contact-content">
              <div class="profile-doc-contact-content-location">
                <h4 class="profile-doc-contact-content-location-title">Onde</h4>
                <p class="profile-doc-contact-content-location-info"><%= @doctor.address %></p>
              </div>
              <div class="profile-doc-contact-content-phone">
                <h4 class="profile-doc-contact-content-location-title">Contato</h4>
                <p class="profile-doc-contact-content-location-info"><%= @doctor.user.phone %></p>
                <p class="profile-doc-contact-content-location-info"><%= @doctor.user.email %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% unless @doctor.work_schedule.work_days.empty? %>
      <div class="appointment-wrapper">
        <div class="appointment-inner">
          <div class="appointment-title">
            <h3 class="appointment-title-content">Atendimento</h3>
            <% @doctor.work_schedule.work_days.each do |weekday| %>
            <p>
              <%= t(Date::DAYNAMES[weekday.day]) %>
            </p>
            <% end %>
          </div>
          <div class="appointment-book" style="width: 100%;">
            <%= simple_form_for @consultation, url: new_doctor_consultation_path(params[:id]), method: :get do |f| %>
            <div class="form-book-outter">
              <div class="form-book">
                <%= f.label "Selecione o dia", { class: 'label-agendamento' } %>
                <%= f.date_field :start_time, data_provide: :datepicker %>
              </div>
              <%= f.submit "agendar", { class: 'btn-coral btn-book'} %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </section>


    <section class="about-doc">
      <div class="about-doc-wrapper">
        <div class="about-doc-inner">
          <div class="about-doc-title">
            <h3 class="about-doc-title-content">Sobre</h3>
          </div>

          <div class="about-doc-details">
            <div class="about-doc-details-specialty">
              <h3>Especialidades</h3>
              <span>
                <% @doctor.specialties.each do |specialty| %>
                <p> <%= specialty.name %> </p>
                <% end %>
              </span>
            </div>
            <div class="about-doc-details-consultation">
              <h3>Consulta</h3>
              <p><%= humanized_money_with_symbol(@doctor.price) %></p>
              <p>1 hora</p>
            </div>
            <div class="about-doc-details-gender">
            </div>
            <div class="about-doc-details-years">
              <h3>Experiência</h3>
              <p><%= @doctor.since %> anos</p>
            </div>
            <div class="about-doc-details-jobs">
              <h3>Experiência Profissional</h3>
              <p><%= @doctor.description %></p>
            </div>
            <div class="about-doc-details-academic">
              <h3>Formação Acadêmica</h3>
              <p><%= @doctor.academic_formation %></p>
            </div>
          </div>

        </div>
      </div>

    </section>

    <section class="map-doc">
      <div class="map-doc-wrapper">
        <div class="map-doc-inner">
          <div id="map"
          style="width: 100%; height: 350px; border-radius: 4px"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
      </section>

      <section class="review-doc-wrapper">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-md-12">
              <div class="review-doc-info">
                <h3>Avaliações de pacientes</h3>
                <% if @reviews.size >= 1 %>
                <h4 class ="form-text"> <strong>Nota geral:</strong></h4>
                <% end %>
                <% @general_rating.times do |star| %>
                <i class="fas fa-star star-icon"></i>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-md-12">
              <div class="reviews">

                <% if @reviews.size >= 1 %>
                <% @reviews.each do |review| %>
                <div class="message">
                  <%= cl_image_tag (review.user.profile_picture), class:"avatar-large" %>
                  <div class="message-name">
                    <h3><%= review.user.first_name %></h3>
                  </div>
                  <div class="message-body">
                    <p><strong><%= review.title %></strong></p>
                    <p>
                      <%= review.content %>
                    </p>
                  </div>
                  <div class="message-status">
                    <% review.rating.times do |star| %>
                    <i class="fas fa-star star-icon"></i>
                    <% end %>
                  </div>
                </div>

                <% end %>
                <% else %>
                <div class = "review-text">
                  <% if current_user %>
                  <% if policy(@doctor).patient? %>
                  <h5>Seja o primeiro a avaliar este médico</h5>
                  <% elsif current_user.doctor != @doctor %>
                  <h5>Este médico ainda não possui avaliações</h5>
                  <% else %>
                  <h5>Você ainda não possui avaliações</h5>
                  <% end %>
                  <% end %>
                  <h5>Este médico ainda não possui avaliações</h5>
                </div>
                <% end %>
              </div>
            </div>
          </div>
          <% if current_user %>
          <% if current_user.doctor != @doctor %>
          <div class="row review-form form-text">
            <% if policy(@doctor).patient? %>
            <div class="col-xs-12 col-md-12 col-xs-offset-3 ">
              <%= simple_form_for([@doctor, @review]) do |f| %>
              <div class="form-inputs">
                <%= f.input :title %>
                <%= f.input :content %>
              </div>
              <div class="d-flex">
                <%= f.input :rating, as: :radio_buttons, collection: ['Excelente', 'Boa', 'Poderia ser melhor', 'Ruim', 'Péssima'], label: 'Como foi sua experiencia?',  class: 'd-flex' %>
              </div>
              <%= f.submit "Enviar Avaliação", class: 'btn-coral' %>
              <% end %>
            </div>
            <% end %>
          </div>
          <% end %>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</div>
<!-- <h1>Dr. <%= @doctor.user.first_name %> <%= @doctor.user.last_name %></h1>
<h2>Price: <%= humanized_money_with_symbol(@doctor.price) %></h2>
<%= link_to "Book", new_doctor_consultation_path(params[:id]) %>
-->

<!-- <%= humanized_money_with_symbol(@doctor.price) %> -->

app/views/doctors/specialties.html.erb
@doctor.user.name
@doctor.address